// <auto-generated />
namespace DatacenterMap.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Corrigindolengthdeatributo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Corrigindolengthdeatributo));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121912107_Corrigindo length de atributo."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
